apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "master-app"
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: "argocd"
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: "argo-apps/"
    repoURL: git@github.com:zetsub0u/tinycorp.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
